name: ASID
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-composer:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Composer build
        run: |
          composer install --no-dev --prefer-dist --no-progress
          composer dump-autoload -o
      - name: Create deployment artifact
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: zip "${REPO_NAME}".zip --exclude=*.git --exclude=node_modules *
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v2
        with:
          name: "${REPO_NAME}"
          path: "${REPO_NAME}".zip