name: ASID
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-composer:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: art-show-id
      - run: cd art-show-id && ls -la
      - name: action-zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r art-show-id.zip art-show-id
      - run: ls -la
      - run: cd art-show-id & ls -la
      - name: Composer build
        run: |
          composer install --no-dev --prefer-dist --no-progress
          composer dump-autoload -o
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: art-show-id
          path: art-show-id.zip