name: ASID
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-composer:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Composer build
        run: |
          composer install --no-dev --prefer-dist --no-progress
          composer dump-autoload -o
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: art-show-id
          path: artikus11/art-show-id/art-show-id.zip