name: ASID
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-composer:
    runs-on: "ubuntu-latest"
    steps:
      - run: cd art-show-id && ls -la
      - name: Checkout code
        uses: actions/checkout@v3
      - run: mkdir -p ./artifact
      - name: Composer build
        run: |
          composer install --no-dev --prefer-dist --no-progress
          composer dump-autoload -o
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./artifact