name: art-show-id
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build project
    runs-on: "ubuntu-latest"
    steps:
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Set up Composer caching
        uses: actions/cache@v2
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies in prod version
        run: |
          composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          make install-prod
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create deployment artifact
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ${{ github.workflow }}.zip
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.workflow }}
          path: ${{ github.workflow }}.zip
  release:
    name: Release project
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.workflow }}
      - name: Get Changelog Entry
        id: changelog-reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: CHANGELOG.md
      - name: Create Release
        id: create-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.changelog-reader.outputs.version }}
      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ github.workflow }}.zip
          asset_name: ${{ github.workflow }}.zip
          asset_content_type: application/zip
