name: ASID
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-composer:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Composer build
        run: |
          composer install --no-dev --prefer-dist --no-progress
          composer dump-autoload -o
      - name: Create deployment artifact
        run: art-show-id.zip --exclude=*.git --exclude=node_modules *

      - name: Store artifact for distribution
        uses: actions/upload-artifact@v2
        with:
          name: art-show-id
          path: art-show-id.zip